/**
 * The failsafe-parity decision, separated from the mirror that acts on it.
 *
 * `mirror.ts` used to compute `onlyNeon = neonTables.filter(...)`, print it as
 * `Missing on Supabase (skipped)`, mirror the tables that matched, and exit 0
 * having printed "MIRROR VERIFIED". A failsafe missing `_prisma_migrations`
 * therefore reported healthy, while `tools/migrate/guards/require-backup.ts`
 * — correct, and unchanged by this work — refused every deploy against it with
 * "a mirror missing tables is not a backup". The operator was told the mirror
 * was fine by the mirror and told it was not a backup by the guard, with
 * nothing explaining the gap.
 *
 * So the decision lives here, as pure functions, and `mirror.ts` routes through
 * it. The split is the point: a pure function can be tested against the exact
 * shapes that occur, and `mirror.ts` cannot — its I/O is two live databases.
 *
 * Provisioning is a reviewed DDL file applied through `apply-schema.ts`, never
 * DDL generated at mirror time. Generating `CREATE TABLE` from a diff of two
 * live schemas at 2am is how a failsafe quietly stops being a restore point.
 */

/**
 * Prisma's migration ledger. `tools/migrate` reads `max(finished_at)` from it
 * to find the last applied migration, so a failsafe without it cannot report
 * which migrations ran — which is why a missing ledger is a parity failure
 * rather than a table the mirror may leave to Prisma.
 */
export const LEDGER_TABLE = "_prisma_migrations";

/**
 * The reviewed DDL that brings the failsafe up to the primary's table set.
 * Generated by `gen-parity-ddl.ts`, reviewed, then applied atomically by
 * `apply-schema.ts`. A path relative to the repo root, so the commands this
 * module prints can be pasted as-is.
 */
export const PARITY_DDL_FILE = "tools/db-mirror/failsafe-parity.sql";

/** How the two databases' table sets compare. */
export interface FailsafeParity {
  /** True when the failsafe holds every table the primary does. */
  readonly complete: boolean;
  /** On the primary, absent from the failsafe. Sorted, deduplicated. */
  readonly missingOnFailsafe: readonly string[];
  /** On the failsafe, absent from the primary. Sorted, deduplicated. */
  readonly extraOnFailsafe: readonly string[];
  /** On both. Sorted, deduplicated. */
  readonly shared: readonly string[];
}

/**
 * Compare the primary's table set against the failsafe's.
 *
 * Order-insensitive on input and deterministic on output, because two databases
 * disagreeing about collation must not decide whether the mirror reports itself
 * as complete, and a plan that reorders run to run makes two runs impossible to
 * diff. Duplicated names collapse, so a table is never provisioned twice.
 *
 * A table on the failsafe but not the primary is EXTRA, never missing: it is
 * not a loss, and it does not make the failsafe incomplete.
 */
export function compareFailsafeParity(
  primary: readonly string[],
  failsafe: readonly string[]
): FailsafeParity {
  const primaryTables = new Set(primary);
  const failsafeTables = new Set(failsafe);

  const missingOnFailsafe = [...primaryTables]
    .filter((table) => !failsafeTables.has(table))
    .sort();
  const extraOnFailsafe = [...failsafeTables]
    .filter((table) => !primaryTables.has(table))
    .sort();
  const shared = [...primaryTables]
    .filter((table) => failsafeTables.has(table))
    .sort();

  return {
    complete: missingOnFailsafe.length === 0,
    missingOnFailsafe,
    extraOnFailsafe,
    shared,
  };
}

/**
 * Why the mirror must refuse, or `null` when it may proceed.
 *
 * `null` rather than a flag, so a caller cannot forget to check it: the only
 * thing between the operator and `bun run db:mirror` returning 0 forever over a
 * partial failsafe is this string being long enough to act on. It names every
 * missing table, says what is wrong, and points at the fix.
 */
export function parityRefusalReason(parity: FailsafeParity): string | null {
  if (parity.complete) return null;

  const missing = parity.missingOnFailsafe;
  return (
    `${missing.length} table(s) missing on the Supabase failsafe: ` +
    `${missing.join(", ")}. A failsafe missing tables is not a backup, and ` +
    `tools/migrate's require-backup guard already refuses every deploy against ` +
    `it. Provision them with ${PARITY_DDL_FILE}, then re-run.`
  );
}

/**
 * The commands that provision the missing tables, in the order to run them.
 *
 * Dry run first, then the apply, so the operator sees what would land before it
 * lands. Both carry `--allow-nonempty` because the failsafe is populated by
 * definition — an apply that omitted it would refuse on the very database it
 * exists to repair. The target is always the failsafe: the primary is read-only
 * to the mirror and is never written to.
 *
 * `tables` states what is being provisioned. It does not change the command,
 * because the DDL is one reviewed file that covers the whole gap — a table-list
 * argument that selected per-table DDL would let a caller provision a subset and
 * call the rest "someone else's".
 */
export function provisioningCommands(
  tables: readonly string[],
  ddlFile: string = PARITY_DDL_FILE
): string[] {
  const script = "bun run tools/db-mirror/apply-schema.ts";
  const target = `${ddlFile} supabase --allow-nonempty`;
  // The flag leads rather than trails, so the two commands differ in the middle
  // and can be compared by eye; a trailing suffix would make them differ only at
  // the very end, where a reader is least likely to notice.
  return [`${script} --dry-run ${target}`, `${script} ${target}`];
}

/** The note that explains the ledger, which an operator is most likely to skip. */
function ledgerNote(table: string): string {
  if (table !== LEDGER_TABLE) return "";
  return (
    ` — the Prisma ledger: tools/migrate reads max(finished_at) from it to find ` +
    `the last applied migration, so a failsafe without it cannot report which ` +
    `migrations ran. It must be provisioned like any other table — the mirror is ` +
    `a copy and must never itself be a migrate deploy target.`
  );
}

/**
 * The operator-facing report, or an empty string when there is nothing to say.
 *
 * Empty when the failsafe is complete and holds nothing extra, so `mirror.ts`
 * can print it unconditionally without a conditional blank line. A missing table
 * is never described as "skipped" — that word is the original defect in two
 * words, telling the operator a class of loss was a deliberate choice.
 */
export function formatParityReport(parity: FailsafeParity): string {
  if (parity.missingOnFailsafe.length === 0 && parity.extraOnFailsafe.length === 0) {
    return "";
  }

  const lines: string[] = [];

  if (parity.missingOnFailsafe.length > 0) {
    lines.push(
      `Supabase failsafe is missing ${parity.missingOnFailsafe.length} table(s) ` +
        `the Neon primary has. Each must be provisioned before the mirror will ` +
        `copy — a failsafe missing tables is not a backup:`
    );
    for (const table of parity.missingOnFailsafe) {
      lines.push(`  - ${table}${ledgerNote(table)}`);
    }
    lines.push("Provision with the reviewed DDL, never DDL generated at mirror time:");
    for (const command of provisioningCommands(parity.missingOnFailsafe)) {
      lines.push(`  ${command}`);
    }
  }

  if (parity.extraOnFailsafe.length > 0) {
    lines.push(
      `Extra on the Supabase failsafe, absent from the primary — left alone: ` +
        `${parity.extraOnFailsafe.join(", ")}`
    );
  }

  return lines.join("\n");
}
